Models/ErrorViewModel.cs
using System;

namespace InspiniaNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
namespace InspiniaNetCore.Controllers
{
    public class CustomerController : Controller
    {
       public IActionResult Contacts()
       {
           return View();
       }
       public IActionResult Contacts_v2()
       {
           return View();
       }
       public IActionResult Contact_List()
       {
           return View();
       }
       public IActionResult Index()
       {
           return View();
       }
       public IActionResult Profile()
       {
           return View();
       }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
namespace InspiniaNetCore.Controllers
{
   public class DashboardsController : Controller
    {
        public IActionResult Dashboard_1()
        {
            return View();
        }

        public IActionResult Dashboard_2()
        {
            return View();
        }

        public IActionResult Dashboard_3()
        {
            return View();
        }

        public IActionResult Dashboard_4()
        {
            return View();
        }

        public IActionResult Dashboard_4_1()
        {
            return View();
        }

        public IActionResult Dashboard_5()
        {
            return View();
        }
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
namespace InspiniaNetCore.Controllers
{
    public class EmployeeController : Controller
    {
        
    }
}

Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace InspiniaNetCore.Controllers
{
    public class BillController : Controller
    {
        
    }
}

Controllers/OrderController.cs
namespace InspiniaNetCore.Controllers
{
    public class OrderController
    {
        
    }
}

Controllers/ProductController.cs
namespace InspiniaNetCore.Controllers
{
    public class ProductController
    {
        
    }
}

Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;

namespace InspiniaNetCore.Controllers
{
    public class SaleController : Controller
    {
        public IActionResult SalePage(){
            return View();
        }
        public IActionResult SaleHistory(){
            return View();
        }
    }
}

Controllers/SystemController.cs
using Microsoft.AspNetCore.Mvc;

namespace InspiniaNetCore.Controllers
{
    public class SystemController : Controller
    {
        
        public IActionResult I18support()
        {
            return View();
        }
    }
}

Controllers/VendorController.cs
namespace InspiniaNetCore.Controllers
{
    public class VendorController
    {
        
    }
}

Views/Customer/Contact_List.cshtml
@{
    ViewData["Title"] = "ContactList";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Customer's list</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Home</a>
            </li>
            <li>
                <a>E-commerce</a>
            </li>
            <li class="active">
                <strong>Product list</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-3">
        <div class="title-action">
            <a href="@Url.Action(" invoicePrint ", "Pages ")" target="_blank" class="btn btn-info">
                <i class="fa fa-file-o"></i> New</a>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">

    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Filter
                <small class="m-l-sm">Filter your typing</small>
            </h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="#">Config option 1</a>
                    </li>
                    <li>
                        <a href="#">Config option 2</a>
                    </li>
                </ul>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-lg-3">
                    <div class="form-group">
                        <label for="Name" class="control-label">Name</label>
                        <input type="text" id="Name" name="Name" value="" placeholder="Customer Name" class="form-control">
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <label for="Address" class="control-label">Address</label>
                        <input type="text" id="Address" name="Address" value="" placeholder="Customer Address" class="form-control">
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <label for="Phone" class="control-label">Phone</label>
                        <input type="text" id="Phone" name="Phone" value="" placeholder="Customer Phone" class="form-control">
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <label for="Group" class="control-label">Group</label>
                        <select name="Group" id="Group" class="form-control">
                            <option value="1" selected="">Enabled</option>
                            <option value="0">Disabled</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>                               
                                <th>Name</th>
                                <th>City</th>
                                <th>District</th>
                                <th>Ward</th>
                                <th>Address</th>
                                <th>Phone Number</th>
                                <th>Email</th>
                                <th>Contact Type</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="gradeX">                                
                                <td>Trident</td>
                                <td>
                                   Bình Dương
                                </td>
                                <td>Phú giáo</td>
                                <td class="center">Phước hòa</td>
                                <td class="center">Phước hòa Phu giao BD</td>
                                <td class="center">1234665</td>
                                <td class="center">acbcomputer@gmail.com</td>
                                <td class="center">Employee</td>
                                <td class="center">
                                    <button class="btn btn-danger btn-xs"> <i class="fa fa-trash"></i> Delete</button>
                                </td>
                            </tr>
                            <tr class="gradeX">                                
                                <td>Trident</td>
                                <td>
                                   Bình Dương
                                </td>
                                <td>Phú giáo</td>
                                <td class="center">Phước hòa</td>
                                <td class="center">Phước hòa Phu giao BD</td>
                                <td class="center">1234665</td>
                                <td class="center">acbcomputer@gmail.com</td>
                                <td class="center">Employee</td>
                                <td class="center">
                                    <button class="btn btn-danger btn-xs"> <i class="fa fa-trash"></i> Delete</button>
                                </td>
                            </tr>
                             <tr class="gradeX">                                
                                <td>Trident</td>
                                <td>
                                   Bình Dương
                                </td>
                                <td>Phú giáo</td>
                                <td class="center">Phước hòa</td>
                                <td class="center">Phước hòa Phu giao BD</td>
                                <td class="center">1234665</td>
                                <td class="center">acbcomputer@gmail.com</td>
                                <td class="center">Employee</td>
                                <td class="center">
                                    <button class="btn btn-danger btn-xs"> <i class="fa fa-trash"></i> Delete</button>
                                </td>
                            </tr>
                             <tr class="gradeX">                                
                                <td>Trident</td>
                                <td>
                                   Bình Dương
                                </td>
                                <td>Phú giáo</td>
                                <td class="center">Phước hòa</td>
                                <td class="center">Phước hòa Phu giao BD</td>
                                <td class="center">1234665</td>
                                <td class="center">acbcomputer@gmail.com</td>
                                <td class="center">Employee</td>
                                <td class="center">
                                    <button class="btn btn-danger btn-xs"> <i class="fa fa-trash"></i> Delete</button>
                                </td>
                            </tr>
                             <tr class="gradeX">                                
                                <td>Trident</td>
                                <td>
                                   Bình Dương
                                </td>
                                <td>Phú giáo</td>
                                <td class="center">Phước hòa</td>
                                <td class="center">Phước hòa Phu giao BD</td>
                                <td class="center">1234665</td>
                                <td class="center">acbcomputer@gmail.com</td>
                                <td class="center">Employee</td>
                                <td class="center">
                                    <button class="btn btn-danger btn-xs"> <i class="fa fa-trash"></i> Delete</button>
                                </td>
                            </tr>                        
                        </tbody>
                        <tfoot>
                            <tr>                               
                                <th>Name</th>
                                <th>City</th>
                                <th>District</th>
                                <th>Ward</th>
                                <th>Address</th>
                                <th>Phone Number</th>
                                <th>Email</th>
                                <th>Contact Type</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables-example').DataTable({
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                        }
                    }
                ]

            });


        });

      
    </script>
}

Views/Miscellaneous/Chat_view.cshtml
@{
    ViewData["Title"] = "Chat_view";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Chat view</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Home</a>
            </li>
            <li>
                <a>Miscellaneous</a>
            </li>
            <li class="active">
                <strong>Chat view</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">

                    <strong>Chat room </strong> can be used to create chat room in your app.
                    You can also use a small chat in the right corner to provide live discussion. 
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">

            <div class="ibox chat-view">

                <div class="ibox-title">
                    <small class="pull-right text-muted">Last message:  Mon Jan 26 2015 - 18:39:23</small>
                    Chat room panel
                </div>


                <div class="ibox-content">

                    <div class="row">

                        <div class="col-md-9 ">
                            <div class="chat-discussion">

                                <div class="chat-message left">
                                    <img class="message-avatar" src="~/Images/a1.jpg" alt="">
                                    <div class="message">
                                        <a class="message-author" href="#"> Michael Smith </a>
                                        <span class="message-date"> Mon Jan 26 2015 - 18:39:23 </span>
                                        <span class="message-content">
                                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                                        </span>
                                    </div>
                                </div>
                                <div class="chat-message right">
                                    <img class="message-avatar" src="~/Images/a4.jpg" alt="">
                                    <div class="message">
                                        <a class="message-author" href="#"> Karl Jordan </a>
                                        <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                        <span class="message-content">
                                            Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover.
                                        </span>
                                    </div>
                                </div>
                                <div class="chat-message left">
                                    <img class="message-avatar" src="~/Images/a2.jpg" alt="">
                                    <div class="message">
                                        <a class="message-author" href="#"> Michael Smith </a>
                                        <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                        <span class="message-content">
                                            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.
                                        </span>
                                    </div>
                                </div>
                                <div class="chat-message right">
                                    <img class="message-avatar" src="~/Images/a5.jpg" alt="">
                                    <div class="message">
                                        <a class="message-author" href="#"> Alice Jordan </a>
                                        <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                        <span class="message-content">
                                            All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
                                            It uses a dictionary of over 200 Latin words.
                                        </span>
                                    </div>
                                </div>
                                <div class="chat-message left">
                                    <img class="message-avatar" src="~/Images/a6.jpg" alt="">
                                    <div class="message">
                                        <a class="message-author" href="#"> Mark Smith </a>
                                        <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                        <span class="message-content">
                                            All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
                                            It uses a dictionary of over 200 Latin words.
                                        </span>
                                    </div>
                                </div>

                            </div>

                        </div>
                        <div class="col-md-3">
                            <div class="chat-users">

                                <div class="users-list">
                                    <div class="chat-user">
                                        <img class="chat-avatar" src="~/Images/a4.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Karl Jordan</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <img class="chat-avatar" src="~/Images/a1.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Monica Smith</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <span class="pull-right label label-primary">Online</span>
                                        <img class="chat-avatar" src="~/Images/a2.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Michael Smith</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <span class="pull-right label label-primary">Online</span>
                                        <img class="chat-avatar" src="~/Images/a3.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Janet Smith</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <img class="chat-avatar" src="~/Images/a5.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Alice Smith</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <img class="chat-avatar" src="~/Images/a6.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Monica Cale</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <img class="chat-avatar" src="~/Images/a2.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Mark Jordan</a>
                                        </div>
                                    </div>
                                    <div class="chat-user">
                                        <span class="pull-right label label-primary">Online</span>
                                        <img class="chat-avatar" src="~/Images/a3.jpg" alt="">
                                        <div class="chat-user-name">
                                            <a href="#">Janet Smith</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="chat-message-form">

                                <div class="form-group">

                                    <textarea class="form-control message-input" name="message" placeholder="Enter message text"></textarea>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="small-chat-box fadeInRight animated">

    <div class="heading" draggable="true">
        <small class="chat-date pull-right">
            02.19.2015
        </small>
        Small chat
    </div>

    <div class="content">

        <div class="left">
            <div class="author-name">
                Monica Jackson <small class="chat-date">
                    10:02 am
                </small>
            </div>
            <div class="chat-message active">
                Lorem Ipsum is simply dummy text input.
            </div>

        </div>
        <div class="right">
            <div class="author-name">
                Mick Smith
                <small class="chat-date">
                    11:24 am
                </small>
            </div>
            <div class="chat-message">
                Lorem Ipsum is simpl.
            </div>
        </div>
        <div class="left">
            <div class="author-name">
                Alice Novak
                <small class="chat-date">
                    08:45 pm
                </small>
            </div>
            <div class="chat-message active">
                Check this stock char.
            </div>
        </div>
        <div class="right">
            <div class="author-name">
                Anna Lamson
                <small class="chat-date">
                    11:24 am
                </small>
            </div>
            <div class="chat-message">
                The standard chunk of Lorem Ipsum
            </div>
        </div>
        <div class="left">
            <div class="author-name">
                Mick Lane
                <small class="chat-date">
                    08:45 pm
                </small>
            </div>
            <div class="chat-message active">
                I belive that. Lorem Ipsum is simply dummy text.
            </div>
        </div>


    </div>
    <div class="form-chat">
        <div class="input-group input-group-sm">
            <input type="text" class="form-control"> <span class="input-group-btn">
                <button class="btn btn-primary" type="button">
                    Send
                </button>
            </span>
        </div>
    </div>

</div>
<div id="small-chat">

    <span class="badge badge-warning pull-right">5</span>
    <a class="open-small-chat">
        <i class="fa fa-comments"></i>

    </a>
</div>

Views/Miscellaneous/CodeEditor.cshtml
@{
    ViewData["Title"] = "CodeEditor";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Code Editor - Code Mirror</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Home</a>
            </li>
            <li>
                <a>Tables</a>
            </li>
            <li class="active">
                <strong>Code Editor</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="col-lg-6">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Code Editor - Basic example</h5>
                </div>
                <div class="ibox-content">

                    <p class="m-b-lg">
                        <strong>CodeMirror</strong> is a versatile text editor implemented in JavaScript for the browser. It is specialized for editing code, and comes with a number of language modes and addons that implement more advanced editing functionality.
                    </p>

                    <textarea id="code1">
<script>
    // Code goes here

    // For demo purpose - animation css script
    function animationHover(element, animation) {
        element = $(element);
        element.hover(
                function () {
                    element.addClass('animated ' + animation);
                },
                function () {
                    //wait for animation to finish before removing classes
                    window.setTimeout(function () {
                        element.removeClass('animated ' + animation);
                    }, 2000);
                });
    }
</script>
                    </textarea>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Code Editor - Theme Example</h5>
                </div>
                <div class="ibox-content">

                    <p class="m-b-lg">
                        A rich programming API and a CSS theming system are available for customizing CodeMirror to fit your application, and extending it with new functionality. For mor info go to
                        <a href="http://codemirror.net/" target="_blank">http://codemirror.net/</a>
                    </p>
                    <textarea id="code2">
<script>
    var SpeechApp = angular.module('SpeechApp', []);

    function VoiceCtrl($scope) {

        $scope.said = '...';

        $scope.helloWorld = function () {
            $scope.said = "Hello world!";
        }

        $scope.commands = {
            'hello (world)': function () {
                if (typeof console !== "undefined") console.log('hello world!')
                $scope.$apply($scope.helloWorld);
            },
            'hey': function () {
                if (typeof console !== "undefined") console.log('hey!')
                $scope.$apply($scope.helloWorld);
            }
        };

        annyang.debug();
        annyang.init($scope.commands);
        annyang.start();
    }
</script>
                    </textarea>
                </div>

            </div>
        </div>
    </div>
</div>

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib_bower/codemirror/lib/codemirror.css" />
        <link rel="stylesheet" href="~/lib_bower/codemirror/theme/ambiance.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib_bower/codemirror/lib/codemirror.js"></script>
        <script src="~/lib_bower/codemirror/mode/javascript/javascript.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            var editor_one = CodeMirror.fromTextArea(document.getElementById("code1"), {
                lineNumbers: true,
                matchBrackets: true,
                styleActiveLine: true,
                theme: "ambiance"
            });

            var editor_two = CodeMirror.fromTextArea(document.getElementById("code2"), {
                lineNumbers: true,
                matchBrackets: true,
                styleActiveLine: true
            });

        });
    </script>
}

Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014 - 2017
    </div>
</div>